services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - testnet

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - testnet

volumes:
  pgdata:

networks:
  testnet:
